### ISSUE TITLE
mobility permissions for package

### ISSUE THREAD

**Issue by kelvan** [kelvan/gotoVienna#16]
gps is not available atm when running gotovienna as user

**Comment by thp** [comment]
See: http://harmattan-dev.nokia.com/docs/library/html/guide/html/Developer_Library_Developing_for_Harmattan_Harmattan_security_Security_guide_Aegis_examples.html

Save as debian/_packagename_.aegis, e.g. debian/gotovienna.aegis:

```
   <aegis>
     <request>
       <credential name="Location" />
       <for path="/path/to/our/main.py" />
     </request>
   </aegis>
```
