### ISSUE TITLE
umlauts in iTip

### ISSUE THREAD

**Issue by chro** [kelvan/gotoVienna#6]
iTip seems not to work with station names containing German umlauts, see e.g.:

root@gamma:/root/kelvan-gotoVienna-6a33e95$ python iTip.py -l 1 -s Börse
Traceback (most recent call last):
  File "iTip.py", line 127, in <module>
    if s.startswith(station[0]) or station[0].startswith(s):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

maybe unicode handling in general is broken?

**Comment by kelvan** [comment]
fixed
please test
